#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.220.131:3306/test?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: root
#    platform: MYSQL
#    continue-on-error: false
#    data: data.sql
#    schema: schema.sql
#    initialize: true
server:
  port: 8088